apiVersion: v2
name: dss
description: A Helm chart to deploy the InterUSS DSS to Kubernetes
type: application
version: 0.1.0
appVersion: "snapshot"
dependencies:
  - name: cockroachdb
    repository: https://charts.cockroachdb.com/
    version: 10.0.7
