# Default configuration
cockroachdb:
  # See https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml
  image:
    repository: cockroachdb/cockroach
  tls:
    certs:
      provided: true
      nodeSecret: cockroachdb.node
      clientRootSecret: cockroachdb.client.root
      selfSigner:
        enabled: false
  ingress:
    enabled: false
