{{- $image := .Values.dss.image }}
{{- $cockroachHost :=  (include "cockroachHost" .) -}}
{{- $jobVersion := .Release.Revision -}} {{/* Jobs template definition is immutable, using the revision in the name forces the job to be recreated at each helm upgrade. */}}
{{- $waitForCockroachDB := include "init-container-wait-for-http" (dict "serviceName" "cockroachdb" "url" (printf "http://%s:8080/health" $cockroachHost)) -}}

{{- range $service, $schemaVersion := dict "rid" "4.0.0" "scd" "3.1.0" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: {{$service}}-schema-manager-{{$jobVersion}}
  name: {{$service}}-schema-manager-{{$jobVersion}}
  namespace: default
spec:
  completions: 1
  parallelism: 1
{{/*  TODO: use selector instead of incrementing jobVersion in name to mitigate immutable template*/}}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: {{$service}}-schema-manager-{{$jobVersion}}
    spec:
      initContainers:
        {{- $waitForCockroachDB | nindent 8 }}
      containers:
        - args:
            - --cockroach_host={{$cockroachHost}}
            - --cockroach_port=26257
            - --cockroach_ssl_dir=/cockroach/cockroach-certs
            - --cockroach_ssl_mode=verify-full
            - --cockroach_user=root
            - --db_version={{$schemaVersion}}
            - --schemas_dir=/db-schemas/{{$service}}
          command:
            - db-manager
          image: {{$image}}
          imagePullPolicy: IfNotPresent
          name: {{$service}}-schema-manager-{{$jobVersion}}
          stdin: false
          tty: false
          volumeMounts:
            {{- include "ca-certs:volumeMount" . | nindent 12 }}
            {{- include "client-certs:volumeMount" . | nindent 12 }}
      imagePullSecrets: []
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      volumes:
        {{- include "ca-certs:volume" . | nindent 8 }}
        {{- include "client-certs:volume" . | nindent 8 }}
{{- end -}}